import { MaterialItem, MaterialCategory } from "./types";

export const MATERIALS: MaterialItem[] = [
  // 1. FABRICS
  {
    id: "boucle-alpaga",
    name: "Bouclé d'Alpaga & Coton",
    category: "fabrics",
    tier: "couture",
    description: "Tissage texturé d'exception en bouclé d'alpaga italien. Toucher cocon d'une volupté incomparable et haute résistance aux frottements.",
    priceModifier: 2400,
    sku: "MAT-BCL-01",
    pbr: { roughness: 0.94, metalness: 0.02, bumpScale: 0.08 },
    thumbnailUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=400&auto=format&fit=crop",
    availableColors: ["ivoire-craie", "sable-chaud", "grege-mineral", "terre-cuite-ourika", "vert-atlas-poudre", "noir-carbone"],
  },
  {
    id: "lin-belge-pur",
    name: "Lin Belge Lavé Lourd",
    category: "fabrics",
    tier: "premium",
    description: "Fibre naturelle de lin cultivé à grain dense (540 g/m²). Tomber souple, respirant et élégance intemporelle pour les intérieurs lumineux.",
    priceModifier: 1200,
    sku: "MAT-LIN-02",
    pbr: { roughness: 0.88, metalness: 0.01, bumpScale: 0.05 },
    thumbnailUrl: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=400&auto=format&fit=crop",
    availableColors: ["ivoire-craie", "sable-chaud", "grege-mineral", "taupe-profond"],
  },
  {
    id: "velours-mohair",
    name: "Velours de Mohair Royal",
    category: "fabrics",
    tier: "couture",
    description: "Reflets profonds et soyeux, densité de poil élevée captant la lumière méditerranéenne avec une noblesse magistrale.",
    priceModifier: 2800,
    sku: "MAT-VLR-03",
    pbr: { roughness: 0.52, metalness: 0.05, clearcoat: 0.4 },
    thumbnailUrl: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=400&auto=format&fit=crop",
    availableColors: ["terre-cuite-ourika", "vert-atlas-poudre", "taupe-profond", "noir-carbone"],
  },
  {
    id: "chenille-coton",
    name: "Chenille Minérale Douce",
    category: "fabrics",
    tier: "standard",
    description: "Fibre veloutée très résistante, facile d'entretien et traitée antitache naturelle sans solvant.",
    priceModifier: 0,
    sku: "MAT-CHN-04",
    pbr: { roughness: 0.82, metalness: 0.02 },
    thumbnailUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=400&auto=format&fit=crop",
    availableColors: ["ivoire-craie", "sable-chaud", "grege-mineral", "noir-carbone"],
  },

  // 2. LEATHERS
  {
    id: "cuir-pleine-fleur",
    name: "Cuir Pleine Fleur de Toscane",
    category: "leathers",
    tier: "couture",
    description: "Tannage végétal artisanal aux extraits d'écorce. Épaisseur 2,2 mm, grain naturel préservé acquérant une patine superbe au fil des décennies.",
    priceModifier: 4500,
    sku: "MAT-CLR-05",
    pbr: { roughness: 0.38, metalness: 0.04, clearcoat: 0.3 },
    thumbnailUrl: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=400&auto=format&fit=crop",
    availableColors: ["cuir-havane-patine", "cuir-ebene-mat", "taupe-profond"],
  },
  {
    id: "cuir-nubuck",
    name: "Cuir Nubuck Velouté",
    category: "leathers",
    tier: "couture",
    description: "Toucher daim velouté d'une infinie douceur, sélection des peaux les plus souples et homogènes.",
    priceModifier: 4900,
    sku: "MAT-NBK-06",
    pbr: { roughness: 0.72, metalness: 0.02 },
    thumbnailUrl: "https://images.unsplash.com/photo-1592078615290-033ee584e267?q=80&w=400&auto=format&fit=crop",
    availableColors: ["sable-chaud", "grege-mineral", "taupe-profond"],
  },

  // 3. WOODS
  {
    id: "noyer-atlas",
    name: "Noyer Massif de l'Atlas",
    category: "woods",
    tier: "premium",
    description: "Essence noble marocaine au veinage contrasté brun chocolat et reflets dorés. Séchage lent en étuve et finition huilée biologique mate.",
    priceModifier: 1800,
    sku: "MAT-NYR-07",
    pbr: { roughness: 0.42, metalness: 0.02, clearcoat: 0.15 },
    thumbnailUrl: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?q=80&w=400&auto=format&fit=crop",
    availableColors: ["noyer-naturel-huile"],
  },
  {
    id: "chene-blanchi",
    name: "Chêne Massif Blanchi",
    category: "woods",
    tier: "standard",
    description: "Chêne de fil clair, brossé pour révéler la texture du bois sous un vernis mat ultra-transparent anti-jaunissement.",
    priceModifier: 0,
    sku: "MAT-CHN-08",
    pbr: { roughness: 0.48, metalness: 0.02 },
    thumbnailUrl: "https://images.unsplash.com/photo-1577140917170-285929fb55b7?q=80&w=400&auto=format&fit=crop",
    availableColors: ["chene-blanchi-nordique"],
  },
  {
    id: "chene-ebene",
    name: "Chêne Noirci au Feu (Shou Sugi Ban)",
    category: "woods",
    tier: "premium",
    description: "Finition inspirée des techniques ancestrales japonaises : bois brûlé superficiellement puis huilé, offrant une texture noire profonde.",
    priceModifier: 1400,
    sku: "MAT-EBN-09",
    pbr: { roughness: 0.35, metalness: 0.05 },
    thumbnailUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=400&auto=format&fit=crop",
    availableColors: ["chene-ebene-brosse"],
  },

  // 4. STONES
  {
    id: "travertin-navona",
    name: "Travertin Romain Navona",
    category: "stones",
    tier: "premium",
    description: "Pierre minérale sédimentaire poreuse taillée dans la masse. Teinte ivoire chaleureuse, arêtes adoucies à l'eau et traitement antitache invisible.",
    priceModifier: 2600,
    sku: "MAT-TRV-10",
    pbr: { roughness: 0.74, metalness: 0.01, bumpScale: 0.07 },
    thumbnailUrl: "https://images.unsplash.com/photo-1615529182904-14819c35db37?q=80&w=400&auto=format&fit=crop",
    availableColors: ["travertin-navona-creme"],
  },
  {
    id: "marbre-noir-marquina",
    name: "Marbre Noir Marquina Adouci",
    category: "stones",
    tier: "couture",
    description: "Marbre noir profond traversé d'élégantes veines blanches de calcite naturelle. Finition cuir satinée au toucher soyeux.",
    priceModifier: 4800,
    sku: "MAT-MRQ-11",
    pbr: { roughness: 0.22, metalness: 0.06, clearcoat: 0.8 },
    thumbnailUrl: "https://images.unsplash.com/photo-1577140917170-285929fb55b7?q=80&w=400&auto=format&fit=crop",
    availableColors: ["marbre-marquina-noir"],
  },
  {
    id: "marbre-calacatta",
    name: "Marbre Blanc Calacatta Gold",
    category: "stones",
    tier: "couture",
    description: "Marbre d'apparat rarissime au fond blanc cristallin zébré de veines dorées et taupe. Présence monumentale souveraine.",
    priceModifier: 6200,
    sku: "MAT-CLC-12",
    pbr: { roughness: 0.18, metalness: 0.06, clearcoat: 0.9 },
    thumbnailUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=400&auto=format&fit=crop",
    availableColors: ["marbre-calacatta-or"],
  },

  // 5. METALS
  {
    id: "laiton-brosse",
    name: "Laiton Massif Brossé Satiné",
    category: "metals",
    tier: "premium",
    description: "Laiton véritable usiné puis brossé à la main, protégé par un vernis satiné cuit au four empêchant l'oxydation tout en préservant son lustre d'or doux.",
    priceModifier: 1500,
    sku: "MAT-LTN-13",
    pbr: { roughness: 0.32, metalness: 0.92, clearcoat: 0.1 },
    thumbnailUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=400&auto=format&fit=crop",
    availableColors: ["laiton-brosse-satine"],
  },
  {
    id: "bronze-obscur",
    name: "Bronze Obscur Patiné",
    category: "metals",
    tier: "premium",
    description: "Patinage chimique à chaud conférant une tonalité chocolat foncé aux reflets cuivrés discrets.",
    priceModifier: 1800,
    sku: "MAT-BRZ-14",
    pbr: { roughness: 0.44, metalness: 0.88 },
    thumbnailUrl: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?q=80&w=400&auto=format&fit=crop",
    availableColors: ["bronze-obscur-patine"],
  },
];

export function getMaterialById(id: string): MaterialItem | undefined {
  return MATERIALS.find((m) => m.id === id);
}

export function getMaterialsByCategory(cat: MaterialCategory): MaterialItem[] {
  return MATERIALS.filter((m) => m.category === cat);
}
