import { ConfiguratorProduct } from "./types";

export const CONFIGURATOR_PRODUCTS: ConfiguratorProduct[] = [
  // ==========================================
  // 1. SOFAS (3 MODELS)
  // ==========================================
  {
    id: "astra-sofa",
    slug: "astra-sofa",
    name: "ASTRA • Canapé Modulaire d'Angle",
    category: "sofas",
    categoryLabel: "Canapés Modulaires",
    tagline: "Architecture Modulaire & Confort Impérial",
    description: "Le summum du living contemporain OÏKOS. Proportions généreuses, assises profondes et méridiennes configurables au centimètre près.",
    story: "Conçu pour habiter les grands salons de réception à Casablanca. La modularité d'ASTRA permet de composer aussi bien une version droite qu'un ensemble d'angle magistral avec méridienne réversible.",
    basePrice: 24000,
    currency: "MAD",
    leadTime: "3 à 4 semaines • Confection personnalisée",
    has3D: true,
    model3DType: "modular-sofa",
    previewImages: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 240, max: 400, step: 10, default: 320, unit: "cm", pricePerStep: 450 },
      depth: { min: 95, max: 120, step: 5, default: 105, unit: "cm", pricePerStep: 300 },
      height: { min: 72, max: 82, step: 2, default: 76, unit: "cm" },
    },
    supportedModules: [
      { id: "mod-linear", name: "Configuration Linéaire 3/4 Places", description: "Banquette continue sans méridienne", type: "standard", priceModifier: 0 },
      { id: "mod-chaise-right", name: "Méridienne Droite d'Angle", description: "Allonge confort côté droit vue de face", type: "chaise-right", priceModifier: 4200 },
      { id: "mod-chaise-left", name: "Méridienne Gauche d'Angle", description: "Allonge confort côté gauche vue de face", type: "chaise-left", priceModifier: 4200 },
      { id: "mod-corner", name: "Angle Complet en L", description: "Retour d'angle avec dossiers enveloppants", type: "corner", priceModifier: 6500 },
    ],
    supportedBases: [
      { id: "base-floating-recessed", name: "Socle Retrait Effet Lévitation", category: "legs", priceModifier: 0, description: "Pieds invisibles en retrait" },
      { id: "base-brass-runners", name: "Patins Laiton Brossé Doré", category: "legs", priceModifier: 1800, hex: "#C5A880", description: "Liseré laiton continu" },
      { id: "base-walnut-frame", name: "Châssis Massif Noyer d'Atlas", category: "base", priceModifier: 2900, hex: "#4A3326", description: "Plateforme bois huilé apparente" },
    ],
    supportedMaterialCategories: ["fabrics", "leathers"],
    defaultConfiguration: {
      dimensions: { width: 320, depth: 105, height: 76 },
      modules: ["mod-chaise-right"],
      materials: { upholstery: "boucle-alpaga" },
      colors: { upholstery: "ivoire-craie" },
      finishes: { legs: "base-floating-recessed" },
      options: { cushionDensity: "moelleux-plume" },
    },
    rules: [
      {
        id: "rule-corner-min-width",
        name: "Largeur Minimale d'Angle",
        description: "Un canapé avec angle complet requiert au minimum 290 cm de largeur",
        condition: { property: "module", operator: "includes", value: "mod-corner" },
        consequence: { type: "enforce_min_dimension", targetPart: "width", targetValue: 290, message: "La configuration en angle requiert au minimum 290 cm de largeur." },
      },
      {
        id: "rule-leather-chaise-width",
        name: "Cuir et Grande Largeur",
        description: "En cuir pleine fleur, la largeur maximale standard est de 360 cm pour garantir l'intégrité des peaux.",
        condition: { property: "material", operator: "equals", value: "cuir-pleine-fleur" },
        consequence: { type: "enforce_max_dimension", targetPart: "width", targetValue: 360, message: "En cuir pleine fleur, la largeur est limitée à 360 cm pour préserver la noblesse des peaux sans couture de raccord." },
      },
    ],
  },
  {
    id: "epure-sofa",
    slug: "epure-sofa",
    name: "ÉPURE • Canapé Linéaire Architectural",
    category: "sofas",
    categoryLabel: "Canapés Droits",
    tagline: "Épure Géométrique & Lignes Minimales",
    description: "Une silhouette basse et tendue inspirée du minimalisme méditerranéen. Dossier bas calibré pour ne jamais encombrer la vue de l'espace.",
    story: "Né de la volonté de créer une assise majestueuse qui s'intègre harmonieusement devant de grandes baies vitrées ou en îlot central.",
    basePrice: 19500,
    currency: "MAD",
    leadTime: "3 semaines",
    has3D: true,
    model3DType: "linear-sofa",
    previewImages: [
      "https://images.unsplash.com/photo-1631679706909-1844bbd07221?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 200, max: 320, step: 10, default: 240, unit: "cm", pricePerStep: 380 },
      depth: { min: 90, max: 110, step: 5, default: 100, unit: "cm", pricePerStep: 250 },
      height: { min: 70, max: 78, step: 2, default: 72, unit: "cm" },
    },
    supportedBases: [
      { id: "base-floating-recessed", name: "Pieds Invisibles", category: "legs", priceModifier: 0 },
      { id: "base-ebonized-wood", name: "Sabots Chêne Noirci", category: "legs", priceModifier: 1200, hex: "#1E1A17" },
    ],
    supportedMaterialCategories: ["fabrics", "leathers"],
    defaultConfiguration: {
      dimensions: { width: 240, depth: 100, height: 72 },
      modules: ["mod-linear"],
      materials: { upholstery: "lin-belge-pur" },
      colors: { upholstery: "sable-chaud" },
      finishes: { legs: "base-floating-recessed" },
      options: {},
    },
    rules: [],
  },
  {
    id: "dune-sofa",
    slug: "dune-sofa",
    name: "DUNE • Canapé Organique Cocon",
    category: "sofas",
    categoryLabel: "Canapés Courbes",
    tagline: "Galbes Sculpturaux & Douceur Dunaire",
    description: "Une ondulation continue sans aucune arête vive. Un véritable havre d'assise enveloppant le corps avec délicatesse.",
    story: "Inspiré par le mouvement perpétuel des dunes du Sahara marocain sculptées par le vent. Une pièce conversationnelle souveraine.",
    basePrice: 22000,
    currency: "MAD",
    leadTime: "3 à 4 semaines",
    has3D: true,
    model3DType: "curved-sofa",
    previewImages: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 230, max: 340, step: 10, default: 270, unit: "cm", pricePerStep: 420 },
      depth: { min: 100, max: 125, step: 5, default: 110, unit: "cm", pricePerStep: 280 },
      height: { min: 72, max: 80, step: 2, default: 74, unit: "cm" },
    },
    supportedMaterialCategories: ["fabrics"],
    defaultConfiguration: {
      dimensions: { width: 270, depth: 110, height: 74 },
      modules: ["mod-linear"],
      materials: { upholstery: "boucle-alpaga" },
      colors: { upholstery: "ivoire-craie" },
      finishes: { legs: "base-floating-recessed" },
      options: {},
    },
    rules: [
      {
        id: "rule-dune-fabrics-only",
        name: "Matières Cintrables",
        description: "DUNE requiert l'élasticité et le gonflant d'un bouclé texturé pour épouser ses courbes sans pli.",
        condition: { property: "material", operator: "equals", value: "cuir-pleine-fleur" },
        consequence: { type: "disable_material", targetValue: "cuir-pleine-fleur", message: "Le modèle DUNE privilégie les tissus bouclés et velours pour préserver la pureté de ses galbes." },
      },
    ],
  },

  // ==========================================
  // 2. ARMCHAIRS (3 MODELS)
  // ==========================================
  {
    id: "galbe-armchair",
    slug: "galbe-armchair",
    name: "GALBE • Fauteuil Sculptural Laiton",
    category: "armchairs",
    categoryLabel: "Fauteuils Sculpturaux",
    tagline: "Courbure d'Exception & Laiton Massif",
    description: "Dialogue entre la chaleur texturée de l'assise et la précision bijoutière d'un piétement cintré en laiton brossé.",
    story: "Pièce Signature de la Maison OÏKOS. Le galbe parfait du dossier nécessite 18 heures d'ajustage manuel par nos maîtres ferronniers.",
    basePrice: 12500,
    currency: "MAD",
    leadTime: "2 à 3 semaines",
    has3D: true,
    model3DType: "sculptural-armchair",
    previewImages: [
      "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 85, max: 105, step: 5, default: 92, unit: "cm", pricePerStep: 200 },
      depth: { min: 80, max: 95, step: 5, default: 88, unit: "cm" },
      height: { min: 74, max: 80, step: 2, default: 76, unit: "cm" },
    },
    supportedBases: [
      { id: "base-brass-arch", name: "Cintre Laiton Massif Brossé", category: "legs", priceModifier: 0, hex: "#C5A880" },
      { id: "base-bronze-dark", name: "Bronze Obscur Médaille", category: "legs", priceModifier: 600, hex: "#3D3428" },
    ],
    supportedMaterialCategories: ["fabrics", "leathers"],
    defaultConfiguration: {
      dimensions: { width: 92, depth: 88, height: 76 },
      modules: ["standard"],
      materials: { upholstery: "velours-mohair" },
      colors: { upholstery: "terre-cuite-ourika" },
      finishes: { legs: "base-brass-arch" },
      options: {},
    },
    rules: [],
  },
  {
    id: "kroma-armchair",
    slug: "kroma-armchair",
    name: "KROMA • Fauteuil Pivotant Club",
    category: "armchairs",
    categoryLabel: "Fauteuils Pivotants",
    tagline: "Rotation Invisible à 360° & Formes Cocon",
    description: "Une assise généreuse montée sur roulement à billes feutré allemand totalement invisible. Confort enveloppant sans compromis.",
    story: "Idéal au centre d'un salon pour converser aussi bien avec l'espace feu que la table à manger.",
    basePrice: 11000,
    currency: "MAD",
    leadTime: "2 semaines",
    has3D: true,
    model3DType: "club-armchair",
    previewImages: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 88, max: 98, step: 5, default: 92, unit: "cm" },
      depth: { min: 86, max: 96, step: 5, default: 90, unit: "cm" },
      height: { min: 72, max: 78, step: 2, default: 75, unit: "cm" },
    },
    supportedMaterialCategories: ["fabrics", "leathers"],
    defaultConfiguration: {
      dimensions: { width: 92, depth: 90, height: 75 },
      modules: ["standard"],
      materials: { upholstery: "boucle-alpaga" },
      colors: { upholstery: "grege-mineral" },
      finishes: { legs: "swivel-concealed" },
      options: {},
    },
    rules: [],
  },
  {
    id: "solis-armchair",
    slug: "solis-armchair",
    name: "SOLIS • Chauffeuse Solitaire Noyer",
    category: "armchairs",
    categoryLabel: "Chauffeuses",
    tagline: "Ébénisterie d'Atlas & Cuir Sellier",
    description: "L'élégance du bois sculpté à queues d'aronde apparentes et assise basse garnie de lin ou cuir naturel.",
    story: "Une ode au geste de l'ébéniste marocain, associant structure ajourée et suspension par sangles de cuir pleine fleur.",
    basePrice: 8900,
    currency: "MAD",
    leadTime: "2 semaines",
    has3D: true,
    model3DType: "sculptural-armchair",
    previewImages: [
      "https://images.unsplash.com/photo-1592078615290-033ee584e267?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 75, max: 85, step: 5, default: 80, unit: "cm" },
      depth: { min: 78, max: 88, step: 5, default: 82, unit: "cm" },
      height: { min: 70, max: 76, step: 2, default: 72, unit: "cm" },
    },
    supportedBases: [
      { id: "base-walnut", name: "Noyer Massif Huilé", category: "base", priceModifier: 0, hex: "#4A3326" },
      { id: "base-ebonized-oak", name: "Chêne Noirci Flammé", category: "base", priceModifier: 600, hex: "#1E1A17" },
    ],
    supportedMaterialCategories: ["fabrics", "leathers"],
    defaultConfiguration: {
      dimensions: { width: 80, depth: 82, height: 72 },
      modules: ["standard"],
      materials: { upholstery: "cuir-pleine-fleur" },
      colors: { upholstery: "cuir-havane-patine" },
      finishes: { base: "base-walnut" },
      options: {},
    },
    rules: [],
  },

  // ==========================================
  // 3. TABLES (3 MODELS)
  // ==========================================
  {
    id: "monolithe-table",
    slug: "monolithe-table",
    name: "MONOLITHE • Table Basse Travertin Navona",
    category: "tables",
    categoryLabel: "Tables Basses Minérales",
    tagline: "Deux Blocs Massifs & Pores Ouverts",
    description: "Deux dalles épaisses taillées dans la masse composent cette table basse iconique. Une présence tellurique et minérale apaisante.",
    story: "Chaque bloc de travertin romain est sélectionné pour l'harmonie de son veinage naturel avant taille et chanfreinage manuel.",
    basePrice: 14000,
    currency: "MAD",
    leadTime: "3 semaines",
    has3D: true,
    model3DType: "monolith-table",
    previewImages: [
      "https://images.unsplash.com/photo-1615529182904-14819c35db37?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 120, max: 180, step: 10, default: 140, unit: "cm", pricePerStep: 450 },
      depth: { min: 70, max: 100, step: 5, default: 80, unit: "cm", pricePerStep: 300 },
      height: { min: 30, max: 38, step: 2, default: 34, unit: "cm" },
    },
    supportedMaterialCategories: ["stones"],
    defaultConfiguration: {
      dimensions: { width: 140, depth: 80, height: 34 },
      modules: ["standard"],
      materials: { tabletop: "travertin-navona" },
      colors: { tabletop: "travertin-navona-creme" },
      finishes: { base: "travertin-navona" },
      options: { finishTreatment: "pores-ouverts-mat" },
    },
    rules: [],
  },
  {
    id: "atlas-table",
    slug: "atlas-table",
    name: "ATLAS • Table d'Apparat Marbre Marquina",
    category: "tables",
    categoryLabel: "Tables Sculpturales",
    tagline: "Marbre Noir d'Exception & Piliers Asymétriques",
    description: "Plateau organique galbé reposant en parfait équilibre sur trois colonnes monolithiques de diamètres distincts.",
    story: "Une sculpture fonctionnelle au veinage blanc vibrant, conçue pour signer avec autorité les pièces de réception les plus exigeantes.",
    basePrice: 28000,
    currency: "MAD",
    leadTime: "4 semaines",
    has3D: true,
    model3DType: "pedestal-table",
    previewImages: [
      "https://images.unsplash.com/photo-1577140917170-285929fb55b7?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 140, max: 200, step: 10, default: 160, unit: "cm", pricePerStep: 600 },
      depth: { min: 80, max: 110, step: 5, default: 95, unit: "cm", pricePerStep: 400 },
      height: { min: 30, max: 36, step: 2, default: 32, unit: "cm" },
    },
    supportedMaterialCategories: ["stones"],
    defaultConfiguration: {
      dimensions: { width: 160, depth: 95, height: 32 },
      modules: ["standard"],
      materials: { tabletop: "marbre-noir-marquina" },
      colors: { tabletop: "marbre-marquina-noir" },
      finishes: { base: "marbre-noir-marquina" },
      options: {},
    },
    rules: [],
  },
  {
    id: "horizon-table",
    slug: "horizon-table",
    name: "HORIZON • Table de Repas Noyer Massif",
    category: "tables",
    categoryLabel: "Tables de Salle à Manger",
    tagline: "Plateau 6 à 12 Couverts & Détails Laiton",
    description: "Épaisseur de plateau de 45 mm en noyer massif sélectionné, biseauté en sous-face pour une légèreté visuelle saisissante.",
    story: "Dessinée pour les dîners d'exception. Les pieds cannelés en bois massif sont cerclés d'un jonc en laiton brossé.",
    basePrice: 21000,
    currency: "MAD",
    leadTime: "3 à 4 semaines",
    has3D: true,
    model3DType: "dining-table",
    previewImages: [
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 200, max: 340, step: 20, default: 260, unit: "cm", pricePerStep: 1200 },
      depth: { min: 95, max: 115, step: 5, default: 105, unit: "cm", pricePerStep: 400 },
      height: { min: 74, max: 76, step: 1, default: 75, unit: "cm" },
    },
    supportedMaterialCategories: ["woods"],
    defaultConfiguration: {
      dimensions: { width: 260, depth: 105, height: 75 },
      modules: ["standard"],
      materials: { tabletop: "noyer-atlas" },
      colors: { tabletop: "noyer-naturel-huile" },
      finishes: { legs: "noyer-atlas" },
      options: { capacity: "8-10 personnes" },
    },
    rules: [],
  },

  // ==========================================
  // 4. BEDS (3 MODELS)
  // ==========================================
  {
    id: "alcove-bed",
    slug: "alcove-bed",
    name: "ALCÔVE • Lit Sommier Bouclé Suspendu",
    category: "beds",
    categoryLabel: "Lits Rembourrés",
    tagline: "Plateforme en Lévitation & Tête Débordante",
    description: "Une tête de lit capitonnée de bouclé d'alpaga débordant de chaque côté pour intégrer tablettes de chevet et liseuses discrètes.",
    story: "Inspiré des suites hôtelières contemporaines les plus raffinées. Le sommier en retrait donne l'impression que le lit flotte sur l'ombre.",
    basePrice: 23000,
    currency: "MAD",
    leadTime: "3 à 4 semaines",
    has3D: true,
    model3DType: "platform-bed",
    previewImages: [
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 180, max: 280, step: 20, default: 220, unit: "cm", pricePerStep: 600 },
      depth: { min: 215, max: 230, step: 5, default: 220, unit: "cm" },
      height: { min: 95, max: 120, step: 5, default: 105, unit: "cm", pricePerStep: 300 },
    },
    supportedBases: [
      { id: "base-floating-led", name: "Socle Retrait avec Éclairage Halo Doré", category: "base", priceModifier: 1500 },
      { id: "base-floating-clean", name: "Socle Retrait Minimaliste", category: "base", priceModifier: 0 },
    ],
    supportedMaterialCategories: ["fabrics", "leathers"],
    defaultConfiguration: {
      dimensions: { width: 220, depth: 220, height: 105 },
      modules: ["standard"],
      materials: { upholstery: "boucle-alpaga" },
      colors: { upholstery: "ivoire-craie" },
      finishes: { base: "base-floating-clean" },
      options: { mattressSize: "180x200 (King Size)" },
    },
    rules: [],
  },
  {
    id: "strate-bed",
    slug: "strate-bed",
    name: "STRATE • Lit Tête Cannelée Chêne Fumé",
    category: "beds",
    categoryLabel: "Lits Architecturaux",
    tagline: "Panneautage Mural Cannelé & Laiton Doré",
    description: "Tête de lit architecturale composée de tasseaux verticaux en chêne massif brossé, alternant ombres et lumière.",
    story: "Une véritable œuvre murale intégrée qui structure la suite parentale avec une rigueur géométrique souveraine.",
    basePrice: 26000,
    currency: "MAD",
    leadTime: "3 à 4 semaines",
    has3D: true,
    model3DType: "fluted-bed",
    previewImages: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 200, max: 320, step: 20, default: 260, unit: "cm", pricePerStep: 800 },
      depth: { min: 215, max: 225, step: 5, default: 220, unit: "cm" },
      height: { min: 110, max: 140, step: 5, default: 120, unit: "cm", pricePerStep: 400 },
    },
    supportedMaterialCategories: ["woods"],
    defaultConfiguration: {
      dimensions: { width: 260, depth: 220, height: 120 },
      modules: ["standard"],
      materials: { headboard: "chene-ebene" },
      colors: { headboard: "chene-ebene-brosse" },
      finishes: { base: "chene-ebene" },
      options: { mattressSize: "180x200 (King Size)" },
    },
    rules: [],
  },
  {
    id: "serena-bed",
    slug: "serena-bed",
    name: "SERENA • Lit Minimaliste Laiton & Cuir",
    category: "beds",
    categoryLabel: "Lits Cuir & Laiton",
    tagline: "Finesse Tubulaire & Coussins Suspendus en Cuir",
    description: "Deux grands coussins de tête en cuir aniline suspendus par des sangles en cuir sellier sur une barre en laiton massif.",
    story: "Pour les amateurs d'épure scandinave et de détails équestres. Légèreté aérienne et douceur tactile du cuir patiné.",
    basePrice: 24500,
    currency: "MAD",
    leadTime: "3 semaines",
    has3D: true,
    model3DType: "platform-bed",
    previewImages: [
      "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=1200&auto=format&fit=crop",
    ],
    dimensions: {
      width: { min: 180, max: 220, step: 20, default: 200, unit: "cm" },
      depth: { min: 210, max: 225, step: 5, default: 215, unit: "cm" },
      height: { min: 100, max: 115, step: 5, default: 105, unit: "cm" },
    },
    supportedMaterialCategories: ["leathers", "fabrics"],
    defaultConfiguration: {
      dimensions: { width: 200, depth: 215, height: 105 },
      modules: ["standard"],
      materials: { headboard: "cuir-pleine-fleur" },
      colors: { headboard: "cuir-havane-patine" },
      finishes: { frame: "laiton-brosse-satine" },
      options: { mattressSize: "180x200 (King Size)" },
    },
    rules: [],
  },
];

export function getProductBySlug(slug: string): ConfiguratorProduct | undefined {
  return CONFIGURATOR_PRODUCTS.find((p) => p.slug === slug || p.id === slug);
}

export function getProductsByCategory(category: string): ConfiguratorProduct[] {
  if (category === "all") return CONFIGURATOR_PRODUCTS;
  return CONFIGURATOR_PRODUCTS.filter((p) => p.category === category);
}
